#!/bin/bash
# Based on:
# http://elinux.org/RPi_Text_to_Speech_(Speech_Synthesis)
# Some extras
# https://travesuras.wordpress.com/2012/01/11/20120111-1/

apt-get update
apt-get upgrade --yes

# Sound utilities
apt-get install --yes alsa-tools alsa-utils

# Install espeak TTS engine
apt-get install --yes espeak

# Primer TTS
espeak -ves "Espeak se ha instalado satisfactoriamente" 2>/dev/null
