#!/bin/bash
# Based on:
# http://elinux.org/RPi_Text_to_Speech_(Speech_Synthesis)
# Some extras
# https://travesuras.wordpress.com/2012/01/11/20120111-1/

apt-get update
apt-get upgrade --yes

# git core
apt-get install --yes git-core
apt-get install --yes autoconf libtool

# Sound utilities
apt-get install --yes alsa-tools alsa-utils

# Install espeak TTS engine
apt-get install --yes espeak

# Pocketsphinx
cd /usr/src
git clone https://github.com/cmusphinx/sphinxbase.git pocketsphinx
cd /usr/src/pocketsphinx

./autogen.sh 
./configure
make clean all
make check
make install

# Primer TTS
# espeak -ves "Espeak se ha instalado satisfactoriamente" 2>/dev/null


